(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function k(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var m="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=aa(this);function p(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var h=a[d];if(!(h in c))break a;c=c[h]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&m(c,a,{configurable:!0,writable:!0,value:b})}}
p("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(e||"")+"_"+h++,e)}function c(e,g){this.g=e;m(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",h=0;return b});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&m(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ba(k(this))}})}return a});function ba(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},q;if("function"==typeof Object.setPrototypeOf)q=Object.setPrototypeOf;else{var r;a:{var da={a:!0},t={};try{t.__proto__=da;r=t.a;break a}catch(a){}r=!1}q=r?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=q;
function v(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(u)u(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.m=b.prototype}var x=this||self;
function y(a,b){function c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.o=function(d,h,e){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[h].apply(d,g)}}function z(a){return a};var A;var B="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;var C=Object,ea=C.freeze,D=[];Object.isFrozen(D)||(B?D[B]|=1:void 0!==D.g?D.g|=1:Object.defineProperties(D,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));ea.call(C,D);var E;function F(a,b){this.g=b===G?a:""}F.prototype.toString=function(){return this.g+""};var G={};/*

 SPDX-License-Identifier: Apache-2.0
*/
try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var fa=/^[\w+/_-]+[=]{0,2}$/;function H(a){this.g=a||x.document||document};function I(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||x,h=d.document,e;if(!(e=a.nonce))a:{e=(d||x).document;if(e.querySelector&&(e=e.querySelector("script[nonce]"))&&(e=e.nonce||e.getAttribute("nonce"))&&fa.test(e))break a;e=""}e&&!a.nonce&&(a.nonce=e);if("help"==a.flow){a:{var g=["document","location","href"];for(var l=d||x,J=0;J<g.length;J++)if(l=l[g[J]],null==l){g=null;break a}g=l}!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;b&&JSON&&JSON.stringify&&(l=JSON.stringify(b),
(g=1200>=l.length)&&(a.psdJson=l));g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);else{d=c+"/load.js?";for(var f in a)b=a[f],(c=null==b)||(c=typeof b,c="object"==c&&null!=b||"function"==c),c||(d+=encodeURIComponent(f)+"="+encodeURIComponent(b)+"&");a=(h?new H(9==h.nodeType?h:h.ownerDocument||h.document):A||(A=new H)).g;f="SCRIPT";"application/xhtml+xml"===a.contentType&&(f=f.toLowerCase());
a=a.createElement(f);e&&a.setAttribute("nonce",e);f=d;if(void 0===E)if(e=null,(d=x.trustedTypes)&&d.createPolicy){try{e=d.createPolicy("asx-frontend#html",{createHTML:z,createScript:z,createScriptURL:z})}catch(ha){x.console&&x.console.error(ha.message)}E=e}else E=e;f=(e=E)?e.createScriptURL(f):f;f=new F(f,G);a.src=f instanceof F&&f.constructor===F?f.g:"type_error:TrustedResourceUrl";var w;f=(a.ownerDocument&&a.ownerDocument.defaultView||window).document;(w=(e=null===(w=f.querySelector)||void 0===
w?void 0:w.call(f,"script[nonce]"))?e.nonce||e.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",w);h.body.appendChild(a)}}function K(a,b,c){I(a,b,c)}var L=["userfeedback","api","startFeedback"],M=x;L[0]in M||"undefined"==typeof M.execScript||M.execScript("var "+L[0]);for(var N;L.length&&(N=L.shift());)L.length||void 0===K?M[N]&&M[N]!==Object.prototype[N]?M=M[N]:M=M[N]={}:M[N]=K;function O(){this.g=this.g}O.prototype.g=!1;O.prototype.isDisposed=function(){return this.g};var P="StopIteration"in x?x.StopIteration:{message:"StopIteration",stack:""};function Q(){}Q.prototype.j=function(){throw P;};Q.prototype.next=function(){return R};var R={done:!0,value:void 0};Q.prototype.h=function(){return this};function ia(a){if(a instanceof S||a instanceof T||a instanceof U)return a;if("function"==typeof a.j)return new S(function(){return V(a)});if("function"==typeof a[Symbol.iterator])return new S(function(){return a[Symbol.iterator]()});if("function"==typeof a.h)return new S(function(){return V(a.h())});throw Error("Not an iterator or iterable.");}
function V(a){if(!(a instanceof Q))return a;var b=!1;return{next:function(){for(var c;!b;)try{c=a.j();break}catch(d){if(d!==P)throw d;b=!0}return{value:c,done:b}}}}function S(a){this.g=a}S.prototype.h=function(){return new T(this.g())};S.prototype[Symbol.iterator]=function(){return new U(this.g())};S.prototype.i=function(){return new U(this.g())};function T(a){this.g=a}v(T,Q);T.prototype.j=function(){var a=this.g.next();if(a.done)throw P;return a.value};T.prototype.next=function(){return this.g.next()};
T.prototype[Symbol.iterator]=function(){return new U(this.g)};T.prototype.i=function(){return new U(this.g)};function U(a){S.call(this,function(){return a});this.l=a}v(U,S);U.prototype.next=function(){return this.l.next()};function ja(){};function W(){}y(W,ja);W.prototype[Symbol.iterator]=function(){return ia(this.h(!0)).i()};function X(a){this.g=a}y(X,W);X.prototype.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};X.prototype.get=function(a){a=this.g.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
X.prototype.h=function(a){var b=0,c=this.g,d=new Q;d.next=function(){if(b>=c.length)return R;var e=c.key(b++);if(a)return{value:e,done:!1};e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return{value:e,done:!1}};var h=d.next;d.j=function(){var e=h.call(d);if(e.done)throw P;return e.value};return d};X.prototype.key=function(a){return this.g.key(a)};function Y(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.g=a}y(Y,X);function Z(){O.call(this);this.i=new Y}v(Z,O);function ka(){var a=new Z,b=a.i.get("GOOGLE_HELP_SESSION_STATE");if(!b)return null;b=JSON.parse(b);var c=(new Date).getTime(),d=b.sessionTimestamp;return!d||"number"!==typeof d||c>d+6E4?(a.i.g.removeItem("GOOGLE_HELP_SESSION_STATE"),null):b};(function(a,b){var c=ka();c&&c["ui-state"]&&(a.flow="help",I(a,b,void 0))}).apply(x,x.GOOGLE_HELP_SESSION_ARGUMENTS);}).call(this);
